//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunting_List_for_MH3U
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Itm
    {
        public DB_Itm()
        {
            this.DB_Itm_Amr = new HashSet<DB_Itm_Amr>();
            this.DB_Itm_Wpn = new HashSet<DB_Itm_Wpn>();
        }
    
        public int Itm_ID { get; set; }
        public Nullable<int> Itm_Rare { get; set; }
        public Nullable<int> Itm_Max { get; set; }
        public Nullable<int> Itm_Sell { get; set; }
        public Nullable<int> Itm_Buy { get; set; }
    
        public virtual ICollection<DB_Itm_Amr> DB_Itm_Amr { get; set; }
        public virtual ICollection<DB_Itm_Wpn> DB_Itm_Wpn { get; set; }
        public virtual ID_Itm_Name ID_Itm_Name { get; set; }
    }
}
