//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunting_List_for_MH3U
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Itm_Wpn
    {
        public int ID { get; set; }
        public Nullable<int> Wpn_ID { get; set; }
        public Nullable<int> Itm_ID { get; set; }
        public Nullable<int> Quant { get; set; }
        public string Type { get; set; }
        public string Region { get; set; }
    
        public virtual DB_Itm DB_Itm { get; set; }
        public virtual DB_Wpn DB_Wpn { get; set; }
    }
}
