//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunting_List_for_MH3U
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_Amr_Name
    {
        public int Amr_ID { get; set; }
        public string Amr_Name_0 { get; set; }
        public string Amr_Name_1 { get; set; }
        public string Amr_Name_2 { get; set; }
        public string Amr_Name_3 { get; set; }
        public string Amr_Name_4 { get; set; }
        public string Amr_Name_5 { get; set; }
        public string Amr_Name_6 { get; set; }
        public string Amr_Name_7 { get; set; }
        public string Amr_Name_8 { get; set; }
        public string Amr_Name_9 { get; set; }
    
        public virtual DB_Amr DB_Amr { get; set; }
    }
}
