//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hunting_List_for_MH3U
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mh3uEntities : DbContext
    {
        public mh3uEntities()
            : base("name=mh3uEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DB_Amr> DB_Amr { get; set; }
        public DbSet<DB_Itm> DB_Itm { get; set; }
        public DbSet<DB_Itm_Amr> DB_Itm_Amr { get; set; }
        public DbSet<DB_Itm_Wpn> DB_Itm_Wpn { get; set; }
        public DbSet<DB_Wpn> DB_Wpn { get; set; }
        public DbSet<ID_Amr_Name> ID_Amr_Name { get; set; }
        public DbSet<ID_Itm_Name> ID_Itm_Name { get; set; }
        public DbSet<ID_Wpn_Name> ID_Wpn_Name { get; set; }
    }
}
